server:
  url: https://ethereum-api.ubex.ai
ethereum:
  socket: /home/ethereum/.ethereum/geth.ipc
  wallet:
    key_file: data/wallets/owner
  address:
    token: 0x1b957dc4aefeed3b4a2351a6a6d5cbfbba0cecfa
    crowdsale: 0xF37c4A962e70d813A4D9825942141Cd9Bc5169Fd
  start_block:
    crowdsale: 4631026
