server:
  url: https://ethereum-api.ubex.ai
ethereum:
  socket: /home/ethereum/.ethereum/geth.ipc
  wallet:
    file: data/wallets/owner
  address:
    token: 0xa6bc42627172cd1da4e3218293df826a37b69131
    crowdsale: 0xa6bc42627172cd1da4e3218293df826a37b69131
  start_block:
    crowdsale: 4631026
